mutation CreateLearningPathItem(
  $participantId: IdOrRef!
  $programId: IdOrRef!
  $title: String!
  $order: Double
  $status: Picklist
  $estimatedWeeks: Double
) {
  uiapi {
    Learning_Path__cCreate(
      input: {
        Learning_Path__c: {
          Participant__c: $participantId
          Program__c: $programId
          Title__c: $title
          Order__c: $order
          Status__c: $status
          Estimated_Weeks__c: $estimatedWeeks
        }
      }
    ) {
      Record {
        Id
      }
    }
  }
}
