query GetAbsence($id: ID!) {
  uiapi {
    query {
      Absence__c(where: { Id: { eq: $id } }, first: 1) {
        edges {
          node {
            Id
            Name @optional { value }
            Participant__c @optional { value }
            Type__c @optional { value }
            Status__c @optional { value }
            StartDate__c @optional { value }
            EndDate__c @optional { value }
            Reason__c @optional { value }
            ApprovedBy__c @optional { value }
            ApprovedAt__c @optional { value }
            RejectedAt__c @optional { value }
            CoachComment__c @optional { value }
            CreatedDate @optional { value }
            LastModifiedDate @optional { value }
            Participant__r @optional {
              Name @optional { value }
            }
            ApprovedBy__r @optional {
              Name @optional { value }
            }
          }
        }
      }
    }
  }
}