query GetParticipant($id: ID!) {
  uiapi {
    query {
      Participant__c(where: { Id: { eq: $id } }, first: 1) {
        edges {
          node {
            Id
            Name @optional {
              value
            }
            Status__c @optional {
              value
            }
            Email__c @optional {
              value
            }
            GitHub__c @optional {
              value
            }
            Discord__c @optional {
              value
            }
            StartDate__c @optional {
              value
            }
            ExpectedEndDate__c @optional {
              value
            }
            Program__c @optional {
              value
            }
            Coach_Profile__c @optional {
              value
            }
          }
        }
      }
    }
  }
}
